- ignore: { name: "Redundant <$>" }
- ignore: { name: "Use ++" }
- ignore: { name: "Use bimap" }
- ignore: { name: "Use const" }
- ignore: { name: "Use first" }
- ignore: { name: "Use second" }
- ignore: { name: "Parenthesize unary negation" }
- ignore: { name: "Functor law" }
