resolver: lts-23.19
packages:
- really-safe-money
- really-safe-money-autodocodec
- really-safe-money-gen

# These are duplicated in nix/overlay.nix
ghc-options:
  "$locals": -Wall -Wincomplete-uni-patterns -Wincomplete-record-updates -Wpartial-fields -Widentities -Wredundant-constraints -Wcpp-undef -Wcpp-undef -O0 -Wunused-packages

system-ghc: true
nix:
  enable: false
with-hpack: hpack
