name: really-safe-money-autodocodec
version: 0.0.0.0
github: "NorfairKing/really-safe-money"
license: AllRightsReserved

extra-source-files:
- test_resources/**/*

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src
  dependencies:
  - autodocodec
  - really-safe-money
  - text

tests:
  really-safe-money-autodocodec-test:
    main: Spec.hs
    build-tools: sydtest-discover
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - aeson
    - autodocodec
    - autodocodec-yaml
    - deepseq
    - genvalidity-sydtest
    - really-safe-money
    - really-safe-money-autodocodec
    - really-safe-money-gen
    - safe-coloured-text
    - sydtest

  really-safe-money-autodocodec-doctest:
    main: DocTest.hs
    source-dirs: doctest/
    ghc-options:              
    - -main-is DocTest     
    - -threaded                            
    - -rtsopts                                
    - -with-rtsopts=-N
    - -Wall        
    dependencies:
    - doctest 

