name: really-safe-money-autodocodec
version: 0.0.0.0
github: "NorfairKing/really-safe-money"
license: AllRightsReserved

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src
  dependencies:
  - autodocodec
  - really-safe-money

tests:
  really-safe-money-autodocodec-doctest:
    main: DocTest.hs
    source-dirs: doctest/
    ghc-options:
    - -main-is DocTest
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
    dependencies:
    - doctest
