name: really-safe-money-autodocodec
version: 0.0.0.0
github: "NorfairKing/really-safe-money"
license: AllRightsReserved

dependencies:
- base >= 4.7 && < 5

flags:
  doctest:
    description: Build the doctest test-suite. Disable under stack, where doctest cannot find the library's dependencies on its load path.
    manual: true
    default: true

library:
  source-dirs: src
  dependencies:
  - autodocodec
  - really-safe-money

tests:
  really-safe-money-autodocodec-doctest:
    main: DocTest.hs
    source-dirs: doctest/
    ghc-options:
    - -main-is DocTest
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
    when:
    - condition: "!flag(doctest)"
      buildable: false
    dependencies:
    - doctest
