name: really-safe-money
version: 0.0.0.0
github: "NorfairKing/really-safe-money"
license: AllRightsReserved

description:         Please see the README on GitHub at <https://github.com/NorfairKing/really-safe-money#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src
  dependencies:
  - containers
  - deepseq
  - validity
  - validity-containers
  - validity-scientific

tests:
  really-safe-money-doctest:
    main: DocTest.hs             
    source-dirs: doctest/
    ghc-options:              
    - -main-is DocTest     
    - -threaded                            
    - -rtsopts                                
    - -with-rtsopts=-N
    - -Wall        
    dependencies:
    - doctest 
