name: really-safe-money-gen
version: 0.0.0.0
github: "NorfairKing/really-safe-money"
license: AllRightsReserved

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src
  dependencies:
  - QuickCheck
  - genvalidity
  - genvalidity-containers
  - really-safe-money

benchmarks:
  smos-data-bench:
    main: Main.hs
    source-dirs: bench/
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
    dependencies:
    - QuickCheck
    - criterion
    - deepseq
    - genvalidity
    - genvalidity-criterion
    - genvalidity-vector
    - really-safe-money
    - really-safe-money-gen
    - vector

tests:
  really-safe-money-test:
    main: Spec.hs
    build-tools: sydtest-discover
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - QuickCheck
    - genvalidity-sydtest
    - genvalidity-vector
    - really-safe-money
    - really-safe-money-gen
    - sydtest
    - vector
